"""
tools.py — Tool definitions and implementations for API Sentinel.

Every tool has two parts:
  1. A JSON schema (TOOL_DEFINITIONS) → what the LLM "sees" and can call
  2. A Python function → what actually executes when the LLM calls it

This separation is the core pattern of any AI agent.
"""

import json
import os
import requests


# ─────────────────────────────────────────────
# HTML template for reports.
# Uses marked.js (CDN) to render Markdown in the browser.
# No extra Python dependencies required.
# ─────────────────────────────────────────────

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>API Sentinel Report</title>
  <script src="https://cdn.jsdelivr.net/npm/marked@9/marked.min.js"></script>
  <style>
    :root {
      --green: #22c55e; --yellow: #f59e0b;
      --red: #ef4444;   --blue: #7dd3fc;
      --bg: #0f172a;    --surface: #1e293b;
      --border: #334155; --text: #e2e8f0;
      --muted: #94a3b8;
    }
    * { box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      max-width: 960px; margin: 0 auto; padding: 2rem 1.5rem;
      background: var(--bg); color: var(--text); line-height: 1.7;
    }
    h1 { color: #f8fafc; border-bottom: 2px solid var(--border); padding-bottom: .5rem; }
    h2 { color: var(--muted); margin-top: 2rem; }
    h3 { color: #cbd5e1; }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; font-size: .9rem; }
    th {
      background: var(--surface); padding: .6rem .75rem;
      text-align: left; color: var(--muted);
      font-size: .78rem; text-transform: uppercase; letter-spacing: .05em;
    }
    td { padding: .6rem .75rem; border-bottom: 1px solid var(--border); }
    tr:hover td { background: var(--surface); }
    code {
      background: var(--surface); padding: .15rem .4rem;
      border-radius: 4px; font-size: .88em; color: var(--blue);
    }
    pre { background: var(--surface); padding: 1rem; border-radius: 8px; overflow-x: auto; }
    pre code { background: none; padding: 0; }
    blockquote {
      border-left: 3px solid var(--border); margin: 0;
      padding: .25rem 1rem; color: var(--muted);
    }
    a { color: var(--blue); }
    strong { color: #f1f5f9; }
    p { margin: .75rem 0; }
    ul, ol { padding-left: 1.5rem; }
    li { margin: .25rem 0; }
    .ok   { color: var(--green); font-weight: 600; }
    .warn { color: var(--yellow); font-weight: 600; }
    .err  { color: var(--red); font-weight: 600; }
    .badge {
      display: inline-block; padding: .1rem .5rem;
      border-radius: 999px; font-size: .8rem; font-weight: 700;
    }
    .footer {
      margin-top: 3rem; padding-top: 1rem;
      border-top: 1px solid var(--border);
      font-size: .8rem; color: var(--muted); text-align: center;
    }
  </style>
</head>
<body>
  <div id="content"></div>
  <div class="footer">Generated by API Sentinel &mdash; AI-powered API testing agent</div>
  <script>
    const md = MARKDOWN_JSON;
    document.getElementById('content').innerHTML = marked.parse(md);

    // Colora le celle con status code nelle tabelle
    document.querySelectorAll('td').forEach(td => {
      const t = td.textContent.trim();
      if (/^2\\d\\d/.test(t))      td.classList.add('ok');
      else if (/^4\\d\\d/.test(t)) td.classList.add('warn');
      else if (/^5\\d\\d/.test(t)) td.classList.add('err');
      else if (t === 'OK' || t === 'Healthy')   td.classList.add('ok');
      else if (t === 'Degraded')                 td.classList.add('warn');
      else if (t === 'Down' || t === 'Critical') td.classList.add('err');
    });
  </script>
</body>
</html>
"""


# ─────────────────────────────────────────────
# 1. Tool schemas (LLM-facing) — OpenAI / litellm format
# ─────────────────────────────────────────────

TOOL_DEFINITIONS = [
    {
        "type": "function",
        "function": {
            "name": "fetch_spec",
            "description": (
                "Fetches and parses an OpenAPI/Swagger specification from a URL or local file. "
                "Returns structured info: API title, version, base URL, and full list of endpoints "
                "with their methods, parameters, and expected response codes."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "source": {
                        "type": "string",
                        "description": "URL or local file path of the OpenAPI spec (must be JSON)"
                    }
                },
                "required": ["source"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "http_request",
            "description": (
                "Makes a real HTTP request to an API endpoint. "
                "Returns status code, reason, response headers, body (truncated at 3000 chars), "
                "and elapsed time in milliseconds."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "url": {
                        "type": "string",
                        "description": "Full URL to call (including query params if needed)"
                    },
                    "method": {
                        "type": "string",
                        "enum": ["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS"],
                        "description": "HTTP method"
                    },
                    "headers": {
                        "type": "object",
                        "description": "Optional HTTP headers as key-value pairs"
                    },
                    "body": {
                        "type": "string",
                        "description": "Optional request body as a JSON string (for POST/PUT/PATCH)"
                    },
                    "timeout": {
                        "type": "integer",
                        "description": "Timeout in seconds (default: 10)"
                    }
                },
                "required": ["url", "method"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "save_report",
            "description": (
                "Saves the analysis report. Always generates BOTH a Markdown (.md) and "
                "an HTML (.html) file in the reports/ directory. Pass the filename without extension."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "filename": {
                        "type": "string",
                        "description": "Base filename without extension (e.g. 'petstore-report')"
                    },
                    "content": {
                        "type": "string",
                        "description": "Full Markdown content of the report"
                    }
                },
                "required": ["filename", "content"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "finish_run",
            "description": (
                "Call this as the LAST step, after save_report. "
                "Records the final test counts for CI/CD exit code evaluation."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "passed":          {"type": "integer", "description": "Endpoints that returned 2xx"},
                    "failed":          {"type": "integer", "description": "Endpoints with 4xx/5xx or network errors"},
                    "skipped":         {"type": "integer", "description": "Endpoints skipped (auth, safe mode, etc.)"},
                    "critical_issues": {"type": "integer", "description": "Number of critical issues found"},
                    "warnings":        {"type": "integer", "description": "Number of warnings"}
                },
                "required": ["passed", "failed", "skipped", "critical_issues", "warnings"]
            }
        }
    }
]


# ─────────────────────────────────────────────
# 2. Tool implementations (Python-facing)
# ─────────────────────────────────────────────

def fetch_spec(source: str) -> dict:
    """Downloads and parses an OpenAPI spec from URL or file."""
    try:
        if source.startswith("http://") or source.startswith("https://"):
            response = requests.get(source, timeout=15)
            response.raise_for_status()
            spec = response.json()
        else:
            with open(source, "r", encoding="utf-8") as f:
                spec = json.load(f)

        info = spec.get("info", {})
        paths = spec.get("paths", {})

        # OpenAPI 3.x uses "servers", Swagger 2.x uses "host" + "basePath"
        servers = spec.get("servers", [])
        host = spec.get("host", "")
        base_path = spec.get("basePath", "")
        schemes = spec.get("schemes", ["https"])

        base_url = ""
        if servers:
            base_url = servers[0].get("url", "")
        elif host:
            base_url = f"{schemes[0]}://{host}{base_path}"

        endpoints = []
        for path, path_item in paths.items():
            for method, operation in path_item.items():
                if method not in ["get", "post", "put", "delete", "patch", "head", "options"]:
                    continue
                endpoints.append({
                    "path": path,
                    "method": method.upper(),
                    "summary": operation.get("summary", ""),
                    "description": operation.get("description", ""),
                    "parameters": operation.get("parameters", []),
                    "request_body": operation.get("requestBody", {}),
                    "expected_responses": list(operation.get("responses", {}).keys()),
                    "tags": operation.get("tags", []),
                    "security": operation.get("security", []),
                    "deprecated": operation.get("deprecated", False)
                })

        return {
            "title": info.get("title", "Unknown API"),
            "version": info.get("version", "?"),
            "description": info.get("description", ""),
            "base_url": base_url,
            "openapi_version": spec.get("openapi") or spec.get("swagger", "?"),
            "endpoint_count": len(endpoints),
            "endpoints": endpoints
        }

    except requests.exceptions.RequestException as e:
        return {"error": f"Failed to fetch spec: {str(e)}"}
    except json.JSONDecodeError as e:
        return {"error": f"Invalid JSON: {str(e)}"}
    except FileNotFoundError:
        return {"error": f"File not found: {source}"}
    except Exception as e:
        return {"error": f"Unexpected error: {str(e)}"}


def http_request(
    url: str,
    method: str,
    headers: dict = None,
    body: str = None,
    timeout: int = 10
) -> dict:
    """Makes a real HTTP request and returns structured response data."""
    try:
        req_headers = headers or {}
        if body and "Content-Type" not in req_headers:
            req_headers["Content-Type"] = "application/json"

        response = requests.request(
            method=method.upper(),
            url=url,
            headers=req_headers,
            data=body,
            timeout=timeout,
            allow_redirects=True
        )

        body_text = response.text[:3000] if response.text else ""
        body_truncated = len(response.text) > 3000 if response.text else False

        return {
            "status_code": response.status_code,
            "reason": response.reason,
            "headers": dict(response.headers),
            "body": body_text,
            "body_truncated": body_truncated,
            "elapsed_ms": int(response.elapsed.total_seconds() * 1000),
            "final_url": str(response.url)
        }

    except requests.exceptions.ConnectionError:
        return {"error": "connection_error", "message": "Host unreachable or DNS resolution failed"}
    except requests.exceptions.Timeout:
        return {"error": "timeout", "message": f"No response after {timeout}s"}
    except requests.exceptions.SSLError as e:
        return {"error": "ssl_error", "message": str(e)}
    except requests.exceptions.TooManyRedirects:
        return {"error": "too_many_redirects", "message": "Redirect loop detected"}
    except Exception as e:
        return {"error": "unknown", "message": str(e)}


def save_report(filename: str, content: str) -> dict:
    """Saves report as both .md and .html in reports/."""
    reports_dir = "reports"
    os.makedirs(reports_dir, exist_ok=True)

    # Normalize: strip extension if present
    base = filename.replace(".md", "").replace(".html", "")

    # Markdown
    md_path = os.path.join(reports_dir, base + ".md")
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(content)

    # HTML — embeds Markdown as a JSON string, rendered by marked.js in the browser
    html_content = _HTML_TEMPLATE.replace("MARKDOWN_JSON", json.dumps(content))
    html_path = os.path.join(reports_dir, base + ".html")
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    return {
        "saved_md": md_path,
        "saved_html": html_path,
        "size_bytes": len(content.encode("utf-8"))
    }


def finish_run(
    passed: int,
    failed: int,
    skipped: int,
    critical_issues: int,
    warnings: int
) -> dict:
    """Records final test counts. Used by CI/CD mode for exit code."""
    status = "healthy" if critical_issues == 0 and failed == 0 else "issues_found"
    return {
        "recorded": True,
        "status": status,
        "passed": passed,
        "failed": failed,
        "skipped": skipped,
        "critical_issues": critical_issues,
        "warnings": warnings
    }


# ─────────────────────────────────────────────
# 3. Router — called by the agent loop
# ─────────────────────────────────────────────

def execute_tool(name: str, inputs: dict) -> str:
    """Routes a tool call by name to its implementation. Returns JSON string."""
    if name == "fetch_spec":
        result = fetch_spec(**inputs)
    elif name == "http_request":
        result = http_request(**inputs)
    elif name == "save_report":
        result = save_report(**inputs)
    elif name == "finish_run":
        result = finish_run(**inputs)
    else:
        result = {"error": f"Unknown tool: {name}"}

    return json.dumps(result, default=str)
